# Generated by Django 5.2.7 on 2025-11-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('temporada', models.CharField(choices=[('Alta', 'Temporada Alta'), ('Media', 'Temporada Media'), ('Baja', 'Temporada Baja')], max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('destinos', models.ManyToManyField(to='cotizador.destino')),
            ],
        ),
    ]
