# Generated by Django 5.2.7 on 2025-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='otro_tipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='¿Cuál?'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='Tipo',
            field=models.CharField(blank=True, choices=[('agencia u operadora', 'Agencia u Operadora'), ('transporte', 'Transporte'), ('hospedaje', 'Hospedaje'), ('alimentacion', 'Alimentación'), ('aseguradora', 'Aseguradora'), ('otros', 'Otros')], max_length=255, null=True),
        ),
    ]
