# Generated by Django 5.2.7 on 2025-11-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_entidad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='Caracteristicas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='NIT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='Nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='RNT',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='Tipo',
            field=models.CharField(choices=[('agencia u operadora', 'Agencia u Operadora'), ('transporte', 'Transporte'), ('hospedaje', 'Hospedaje'), ('alimentacion', 'Alimentación'), ('aseguradora', 'Aseguradora'), ('otros', 'Otros')], default='otros', max_length=255),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='Ubicacion',
            field=models.CharField(default='', help_text='Ingrese las coordenadas de Google Maps (ej: 4.60971, -74.08175)', max_length=255, verbose_name='Ubicación (Coordenadas)'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
