# Generated by Django 5.2.7 on 2025-11-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_alter_entidad_caracteristicas_alter_entidad_nit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentacion',
            options={'verbose_name': 'Alimentacion', 'verbose_name_plural': 'Alimentacion'},
        ),
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destino'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidad'},
        ),
        migrations.AlterModelOptions(
            name='hospedaje',
            options={'verbose_name': 'Hospedaje', 'verbose_name_plural': 'Hospedaje'},
        ),
        migrations.AlterModelOptions(
            name='paquete',
            options={'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquete'},
        ),
        migrations.AlterModelOptions(
            name='seguro',
            options={'verbose_name': 'Seguro', 'verbose_name_plural': 'Seguro'},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'verbose_name': 'Transporte', 'verbose_name_plural': 'Transporte'},
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='password',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='Ubicacion',
            field=models.CharField(default='', help_text='Ingrese las coordenadas de tu ubicación de Google Maps (ej: 4.60971, -74.08175)', max_length=255, verbose_name='Ubicación'),
        ),
    ]
