# Generated by Django 5.2.7 on 2025-11-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_alter_alimentacion_options_alter_destino_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='NIT',
            field=models.CharField(default='', max_length=20),
        ),
    ]
