# Generated by Django 5.2.7 on 2025-11-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_alter_entidad_nit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='Caracteristicas',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='NIT',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='RNT',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='Tipo',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='Ubicacion',
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería'), ('TE', 'Tarjeta de extranjería'), ('PA', 'Pasaporte'), ('DIE', 'Documento de identificación extranjero (genérico)'), ('PPT', 'Permiso por Protección Temporal'), ('PEP', 'Permiso Especial de Permanencia'), ('SCR', 'Salvoconducto'), ('NIT', 'NIT – Número de Identificación Tributaria'), ('NIFE', 'NIT de otro país / Identificador fiscal extranjero'), ('NUIP', 'Número Único de Identificación Personal')], max_length=4, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='otro_tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otro Tipo (si aplica)'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asociado'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='nit',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='NIT o Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='rnt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RNT (Registro Nacional de Turismo)'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipo',
            field=models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica')], default='PN', max_length=2, verbose_name='Tipo de Entidad'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='ubicacion',
            field=models.CharField(default='', max_length=255, verbose_name='Ubicación'),
        ),
    ]
