# Generated by Django 5.2.7 on 2025-11-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_remove_entidad_caracteristicas_remove_entidad_nit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='otro_tipo',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nit',
            field=models.CharField(max_length=20, unique=True, verbose_name='NIT o Documento de Identidad'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='ubicacion',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
    ]
