# Generated by Django 5.2.7 on 2025-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_remove_entidad_otro_tipo_alter_entidad_nit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='tipo',
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurante', 'Restaurante'), ('Agencia de Viajes', 'Agencia de Viajes'), ('Transporte', 'Transporte'), ('Seguro', 'Seguro'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Tipo de Entidad'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='tipo_persona',
            field=models.CharField(choices=[('PN', 'Persona Natural'), ('PJ', 'Persona Jurídica')], default='PN', max_length=2, verbose_name='Tipo de Persona'),
        ),
    ]
