# Generated by Django 5.2.7 on 2025-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_alter_entidad_tipo_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='otro_tipo_entidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar Otro Tipo de Entidad'),
        ),
    ]
