# Generated by Django 5.2.7 on 2025-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0012_entidad_otro_tipo_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TE', 'Tarjeta de extranjería'), ('PA', 'Pasaporte'), ('DIE', 'Documento de identificación extranjero (genérico)'), ('PPT', 'Permiso por Protección Temporal'), ('PEP', 'Permiso Especial de Permanencia'), ('SCR', 'Salvoconducto'), ('NIT', 'NIT – Número de Identificación Tributaria'), ('NIFE', 'NIT de otro país / Identificador fiscal extranjero'), ('NUIP', 'Número Único de Identificación Personal')], max_length=4, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
