# Generated by Django 5.2.7 on 2025-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0013_alter_entidad_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='user',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.CharField(choices=[('Hospedaje', 'Hospedaje -'), ('Alimentación', 'Alimentación -'), ('Operadora Turística', 'Operadora Turística -'), ('Transporte', 'Transporte -'), ('Seguro', 'Seguro -'), ('Otro', 'Otro -')], default='Otro', max_length=50, verbose_name='Tipo de Entidad'),
        ),
    ]
