# Generated by Django 5.2.7 on 2025-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0015_entidad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.CharField(blank=True, choices=[('Hospedaje', 'Hospedaje'), ('Alimentación', 'Alimentación'), ('Operadora Turística', 'Operadora Turística'), ('Transporte', 'Transporte'), ('Seguro', 'Seguro'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Entidad'),
        ),
    ]
