# Generated by Django 5.2.7 on 2025-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0016_alter_entidad_tipo_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la Empresa'),
        ),
    ]
