# Generated by Django 5.2.7 on 2025-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0017_entidad_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Refieren actividades turísticas específicas pertenecientes a la actividad genérica, ej.: agencia de viajes y turismo, agencia de viajes mayorista, hotel, apartahotel, entre otros.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.CharField(blank=True, choices=[('Hospedaje', 'Hospedaje'), ('Alimentación', 'Alimentación'), ('Operadora turística o agencia de viajes', 'Operadora turística o agencia de viajes'), ('Transporte', 'Transporte'), ('Seguro', 'Seguro'), ('Otro', 'Otro')], max_length=50, verbose_name='Categoría'),
        ),
    ]
