# Generated by Django 5.2.7 on 2025-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0018_entidad_subcategoria_alter_entidad_tipo_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
    ]
