# Generated by Django 5.2.7 on 2025-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0019_entidad_departamento_entidad_municipio_entidad_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
