# Generated by Django 5.2.7 on 2025-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0020_entidad_barrio_entidad_direccion_entidad_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='temporadaAlta',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='temporadaBaja',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='temporadaIdeal',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='temporadaMedia',
        ),
        migrations.AddField(
            model_name='destino',
            name='categoria_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar Otra Categoría'),
        ),
        migrations.AddField(
            model_name='destino',
            name='costos_adicionales',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Costos Adicionales'),
        ),
        migrations.AddField(
            model_name='destino',
            name='incluye',
            field=models.TextField(blank=True, null=True, verbose_name='Lo que incluye'),
        ),
        migrations.AddField(
            model_name='destino',
            name='no_incluye',
            field=models.TextField(blank=True, null=True, verbose_name='Lo que no incluye'),
        ),
        migrations.AddField(
            model_name='destino',
            name='precioTemporadaAlta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Temporada Alta'),
        ),
        migrations.AddField(
            model_name='destino',
            name='precioTemporadaBaja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Temporada Baja'),
        ),
        migrations.AddField(
            model_name='destino',
            name='precioTemporadaMedia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Temporada Media'),
        ),
        migrations.AddField(
            model_name='destino',
            name='precio_pasadia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por Día'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='actividades',
            field=models.JSONField(default=list, verbose_name='Atractivos del lugar'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='categoria',
            field=models.CharField(choices=[('Turismo cultural', 'Turismo cultural'), ('Turismo de aventura', 'Turismo de aventura'), ('Ecoturismo', 'Ecoturismo'), ('Turismo gastronómico', 'Turismo gastronómico'), ('Turismo de sol y playa', 'Turismo de sol y playa'), ('Turismo rural', 'Turismo rural'), ('Turismo de salud y bienestar', 'Turismo de salud y bienestar'), ('Turismo religioso', 'Turismo religioso'), ('Turismo histórico', 'Turismo histórico'), ('Turismo de eventos y negocios', 'Turismo de eventos y negocios'), ('Turismo médico', 'Turismo médico'), ('Turismo marino costero', 'Turismo marino costero'), ('Otro', 'Otro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='destino',
            name='duracionRecomendada',
            field=models.CharField(choices=[('Pasadía', 'Pasadía'), ('Por Días', 'Por Días')], max_length=20, verbose_name='Tipo de Duración'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='ubicacion',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
    ]
