# Generated by Django 5.2.7 on 2025-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0021_remove_destino_temporadaalta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='categoria_otro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuál?'),
        ),
    ]
