# Generated by Django 5.2.7 on 2025-11-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0022_alter_destino_categoria_otro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='costos_adicionales',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='duracionRecomendada',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='incluye',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='no_incluye',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='precioTemporadaAlta',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='precioTemporadaBaja',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='precioTemporadaMedia',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='precio_pasadia',
        ),
        migrations.AlterField(
            model_name='destino',
            name='actividades',
            field=models.JSONField(default=list, verbose_name='Atractivos y Costos'),
        ),
    ]
