# Generated by Django 5.2.7 on 2025-11-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0023_remove_destino_costos_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
