# Generated by Django 5.2.7 on 2025-11-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0024_alter_destino_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='cotizador.entidad'),
        ),
    ]
