# Generated by Django 5.2.7 on 2025-11-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0025_destino_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de disponibilidad', null=True),
        ),
    ]
