# Generated by Django 5.2.7 on 2025-11-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0026_alter_alimentacion_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='categoria',
            field=models.CharField(choices=[('Turismo cultural', 'Turismo cultural'), ('Turismo de aventura', 'Turismo de aventura'), ('Ecoturismo', 'Ecoturismo'), ('Turismo gastronómico', 'Turismo gastronómico'), ('Turismo de sol y playa', 'Turismo de sol y playa'), ('Turismo rural', 'Turismo rural'), ('Turismo de salud y bienestar', 'Turismo de salud y bienestar'), ('Turismo religioso', 'Turismo religioso'), ('Turismo histórico', 'Turismo histórico'), ('Turismo de eventos y negocios', 'Turismo de eventos y negocios'), ('Turismo médico', 'Turismo médico'), ('Turismo marino costero', 'Turismo marino costero'), ('Turismo de naturaleza', 'Turismo de naturaleza'), ('Turismo urbano y cultural', 'Turismo urbano y cultural'), ('Turismo ecológico y de aventura', 'Turismo ecológico y de aventura'), ('Turismo cultural y natural', 'Turismo cultural y natural'), ('Otro', 'Otro')], max_length=255),
        ),
    ]
