# Generated by Django 5.2.7 on 2025-11-20 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0030_alter_destino_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentacion',
            options={'verbose_name': 'Alimentacion', 'verbose_name_plural': 'Alimentaciones'},
        ),
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='hospedaje',
            options={'verbose_name': 'Hospedaje', 'verbose_name_plural': 'Hospedajes'},
        ),
        migrations.AlterModelOptions(
            name='paquete',
            options={'verbose_name': 'Paquete', 'verbose_name_plural': 'Paquetes'},
        ),
        migrations.AlterModelOptions(
            name='seguro',
            options={'verbose_name': 'Seguro', 'verbose_name_plural': 'Seguros'},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='ambiance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ambiente/Temática'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad (número de asientos)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Contacto'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Internacional', 'Internacional'), ('Italiana', 'Italiana'), ('Mexicana', 'Mexicana'), ('Asiatica', 'Asiática'), ('Fusion', 'Fusión'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Tipo de Cocina'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='dietary_options',
            field=models.JSONField(blank=True, default=list, verbose_name='Opciones Dietéticas'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion_services', to='cotizador.entidad'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alimentacion_services/', verbose_name='Imagen del Plato/Servicio'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='meal_type',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Snack', 'Snack'), ('Cocteles', 'Cocteles'), ('Bar', 'Bar'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Tipo de Comida/Servicio'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horario de Apertura'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='other_cuisine_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar Otro Tipo de Cocina'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='other_dietary_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Especificar Otras Opciones Dietéticas'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_11_20',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_21_30',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_31_50',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_50_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_5_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='special_features',
            field=models.TextField(blank=True, null=True, verbose_name='Características Especiales (ej. música en vivo, terraza)'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='cotizador.entidad'),
        ),
    ]
