# Generated by Django 5.2.7 on 2025-11-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0031_alter_alimentacion_options_alter_destino_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospedajes', to='cotizador.entidad'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='cotizador.entidad'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='cotizador.entidad'),
        ),
    ]
