# Generated by Django 5.2.7 on 2025-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0034_auto_20251123_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='aire_acondicionado',
            field=models.BooleanField(default=False, verbose_name='Aire acondicionado'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula del vehículo'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='modeloTransporte',
            field=models.CharField(blank=True, choices=[('BUS_GRANDE', 'Bus grande (> 30 pax)'), ('MINIBUS', 'Minibus (15-30 pax)'), ('VAN', 'Van (7-15 pax)'), ('SUV_4X4', 'SUV 4X4 (Privado/Aventura)'), ('AUTOMOVIL', 'Automóvil (Sedán estándar/luxury)'), ('JEEP_WILLYS', 'Jeep Willys (Cultural Eje Cafetero)'), ('CHIVA', 'Chiva (Cultural Grupal)'), ('MOTOCARRO', 'Motocarro (Tuk-tuk)'), ('BUGGY', 'Buggy (Aventura)')], max_length=255, null=True, verbose_name='Modelo de transporte'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='sillas_reclinables',
            field=models.BooleanField(default=False, verbose_name='Sillas reclinables'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='tipo_transporte',
            field=models.CharField(choices=[('aereo', 'Aéreo'), ('terrestre', 'Terrestre'), ('maritimo', 'Marítimo')], default='terrestre', max_length=255, verbose_name='Tipo de transporte'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='cantidad',
            field=models.IntegerField(blank=True, help_text='Cantidad de vehículos', null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='pax',
            field=models.IntegerField(blank=True, help_text='Capacidad en número de pasajeros', null=True),
        ),
    ]
