# Generated by Django 5.2.7 on 2025-11-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0036_alter_transporte_fields'),
    ]

    operations = [
        # Cambiar nombres de campos para que coincidan con el nuevo modelo
        migrations.RenameField(
            model_name='transporte',
            old_name='nombre',
            new_name='nombre_temporal',
        ),
    ] + [
        # Eliminar el campo temporal y agregar los nuevos campos
        migrations.RemoveField(
            model_name='transporte',
            name='nombre_temporal',
        ),
        migrations.AddField(
            model_name='transporte',
            name='modelo_vehiculo',
            field=models.CharField(max_length=255, verbose_name="Modelo", blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='cantidad_vehiculos',
            field=models.IntegerField(verbose_name="Cantidad Vehículos", blank=True, null=True, help_text="Cantidad de vehículos"),
        ),
        migrations.AddField(
            model_name='transporte',
            name='capacidad_vehiculo_pax',
            field=models.IntegerField(verbose_name="Capacidad Vehículo Pax", blank=True, null=True, help_text="Capacidad en número de pasajeros"),
        ),
        migrations.AddField(
            model_name='transporte',
            name='conexion_usb',
            field=models.BooleanField(verbose_name="Conexión USB", default=False),
        ),
    ] + [
        # Actualizar campos existentes para nuevos nombres de verbose_name
        migrations.AlterField(
            model_name='transporte',
            name='matricula',
            field=models.CharField(max_length=255, verbose_name="Matrícula", blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='cantidad',
            field=models.IntegerField(verbose_name="Cantidad Vehículos", blank=True, null=True, help_text="Cantidad de vehículos"),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='pax',
            field=models.IntegerField(verbose_name="Capacidad Vehículo Pax", blank=True, null=True, help_text="Capacidad en número de pasajeros"),
        ),
    ]