# Generated by Django 5.2.8 on 2025-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0037_update_transporte_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='cantidad_vehiculos',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='capacidad_vehiculo_pax',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='conexion_usb',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='modelo_vehiculo',
        ),
        migrations.AddField(
            model_name='transporte',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='cantidad',
            field=models.IntegerField(blank=True, help_text='Cantidad de vehículos', null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula del vehículo'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='pax',
            field=models.IntegerField(blank=True, help_text='Capacidad en número de pasajeros', null=True),
        ),
    ]
