# Generated by Django 5.2.7 on 2025-11-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0039_auto_20251123_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='tipo_pantallas',
            field=models.CharField(choices=[('puesto', 'En cada puesto'), ('comunitario', 'Comunitarias/Generales')], default='comunitario', help_text='Indicar si las pantallas son en cada puesto o comunitarias/generales', max_length=20, verbose_name='Tipo de Pantallas'),
        ),
    ]
