# Generated by Django 5.2.7 on 2025-11-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0040_transporte_tipo_pantallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='transportes/', verbose_name='Imagen del vehículo'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='imagenes',
            field=models.JSONField(blank=True, default=list, verbose_name='Más imágenes'),
        ),
    ]
