# Generated by Django 5.2.7 on 2025-11-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0041_transporte_imagen_transporte_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(max_length=255, verbose_name='Ciudad de Origen')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Convenio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización del Convenio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('entidad_agencia', models.ForeignKey(limit_choices_to={'tipo_entidad': 'Operadora turística o agencia de viajes'}, on_delete=django.db.models.deletion.CASCADE, related_name='convenios_agencia', to='cotizador.entidad', verbose_name='Agencia de Viajes')),
                ('entidad_transportadora', models.ForeignKey(limit_choices_to={'tipo_entidad': 'Transporte'}, on_delete=django.db.models.deletion.CASCADE, related_name='convenios_transportadora', to='cotizador.entidad', verbose_name='Transportadora')),
            ],
            options={
                'verbose_name': 'Convenio Transporte',
                'verbose_name_plural': 'Convenios Transporte',
            },
        ),
        migrations.CreateModel(
            name='RutaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_destino', models.CharField(max_length=255, verbose_name='Ciudad de Destino')),
                ('precio_alta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Temporada Alta')),
                ('precio_media', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Temporada Media')),
                ('precio_baja', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Temporada Baja')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='cotizador.conveniotransporte', verbose_name='Convenio')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.destino', verbose_name='Destino')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.paquete', verbose_name='Paquete')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='cotizador.transporte', verbose_name='Vehículo/Transporte')),
            ],
            options={
                'verbose_name': 'Ruta de Transporte',
                'verbose_name_plural': 'Rutas de Transporte',
            },
        ),
    ]
