# Generated by Django 5.2.7 on 2025-11-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0042_conveniotransporte_rutatransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutatransporte',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='cotizador.conveniotransporte', verbose_name='Convenio Transporte'),
        ),
        migrations.CreateModel(
            name='ConvenioAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_convenio', models.CharField(choices=[('Transporte', 'Transporte'), ('Alimentación', 'Alimentación'), ('Hospedaje', 'Hospedaje'), ('Seguro', 'Seguro'), ('Otro', 'Otro')], max_length=20, verbose_name='Tipo de Convenio')),
                ('ciudad_origen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad de Origen')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Convenio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización del Convenio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Convenio')),
                ('entidad_agencia', models.ForeignKey(limit_choices_to={'tipo_entidad': 'Operadora turística o agencia de viajes'}, on_delete=django.db.models.deletion.CASCADE, related_name='convenios_como_agencia', to='cotizador.entidad', verbose_name='Agencia de Viajes')),
                ('entidad_convenio', models.ForeignKey(help_text='Transportadora, Alimentación, Hospedaje, Seguro u otro tipo de entidad', on_delete=django.db.models.deletion.CASCADE, related_name='convenios_con_agencias', to='cotizador.entidad', verbose_name='Empresa con Convenio')),
            ],
            options={
                'verbose_name': 'Convenio de Agencia',
                'verbose_name_plural': 'Convenios de Agencia',
            },
        ),
        migrations.AddField(
            model_name='rutatransporte',
            name='convenio_agencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='cotizador.convenioagencia', verbose_name='Convenio de Agencia'),
        ),
    ]
