# Generated by Django 5.2.7 on 2025-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0043_alter_rutatransporte_convenio_convenioagencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutatransporte',
            name='ciudad_destino',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad de Destino'),
        ),
    ]
