# Generated by Django 5.2.7 on 2025-11-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0044_alter_rutatransporte_ciudad_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutatransporte',
            name='convenio',
        ),
    ]
