# Generated by Django 5.2.7 on 2025-11-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0045_remove_rutatransporte_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.CharField(blank=True, choices=[('Hospedaje', 'Hospedaje'), ('Operadora turística o agencia de viajes', 'Operadora turística o agencia de viajes'), ('Transporte', 'Transporte'), ('Seguro', 'Seguro'), ('Otro', 'Otro')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='Alimentacion',
        ),
    ]
