# Generated by Django 5.2.7 on 2025-11-25 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0046_alter_entidad_tipo_entidad_delete_alimentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='tipo_entidad',
            field=models.CharField(blank=True, choices=[('Hospedaje', 'Hospedaje'), ('Alimentación', 'Alimentación'), ('Operadora turística o agencia de viajes', 'Operadora turística o agencia de viajes'), ('Transporte', 'Transporte'), ('Seguro', 'Seguro'), ('Otro', 'Otro')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.JSONField(blank=True, default=list, verbose_name='Tipo de Comida/Servicio')),
                ('servicios_tipo', models.JSONField(blank=True, default=list, verbose_name='Tipo de Plan y Cocina')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona')),
                ('price_group_5_10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas)')),
                ('price_group_11_20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas)')),
                ('price_group_21_30', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas)')),
                ('price_group_31_50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas)')),
                ('price_group_50_plus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas)')),
                ('dietary_options', models.JSONField(blank=True, default=list, verbose_name='Opciones Dietéticas')),
                ('other_dietary_options', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especificar Otras Opciones Dietéticas')),
                ('opening_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horario de Apertura')),
                ('closing_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horario de Cierre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='alimentacion_services/', verbose_name='Imagen del Plato/Servicio')),
                ('desayunoContinental', models.BooleanField(default=False)),
                ('desayunoAmericano', models.BooleanField(default=False)),
                ('desayunoBuffet', models.BooleanField(default=False)),
                ('almuerzo', models.BooleanField(default=False)),
                ('cena', models.BooleanField(default=False)),
                ('snacks', models.BooleanField(default=False)),
                ('barAbierto', models.BooleanField(default=False)),
                ('barCerrado', models.BooleanField(default=False)),
                ('bebidasNacionales', models.BooleanField(default=False)),
                ('bebidasInternacionales', models.BooleanField(default=False)),
                ('bebidasNoAlcoholicas', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de disponibilidad', null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('incluyePropinas', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('restricciones', models.JSONField(default=list)),
                ('horariosServicio', models.CharField(blank=True, max_length=255, null=True)),
                ('opcionVegana_disponible', models.BooleanField(default=False)),
                ('opcionVegana_descripcion', models.TextField(blank=True, null=True)),
                ('opcionVegana_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opcionVegetariana_disponible', models.BooleanField(default=False)),
                ('opcionVegetariana_descripcion', models.TextField(blank=True, null=True)),
                ('opcionVegetariana_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opcionSinGluten_disponible', models.BooleanField(default=False)),
                ('opcionSinGluten_descripcion', models.TextField(blank=True, null=True)),
                ('opcionSinGluten_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opcionMariscos_disponible', models.BooleanField(default=False)),
                ('opcionMariscos_descripcion', models.TextField(blank=True, null=True)),
                ('opcionMariscos_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opcionGastronomiaLocal_disponible', models.BooleanField(default=False)),
                ('opcionGastronomiaLocal_descripcion', models.TextField(blank=True, null=True)),
                ('opcionGastronomiaLocal_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opcionKosher_disponible', models.BooleanField(default=False)),
                ('opcionKosher_descripcion', models.TextField(blank=True, null=True)),
                ('opcionKosher_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opcionHalal_disponible', models.BooleanField(default=False)),
                ('opcionHalal_descripcion', models.TextField(blank=True, null=True)),
                ('opcionHalal_precioAdicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion_services', to='cotizador.entidad')),
            ],
            options={
                'verbose_name': 'Alimentacion',
                'verbose_name_plural': 'Alimentaciones',
            },
        ),
    ]
