# Generated by Django 5.2.7 on 2025-11-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0047_alter_entidad_tipo_entidad_alimentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentacion',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='barAbierto',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='barCerrado',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='bebidasInternacionales',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='bebidasNacionales',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='bebidasNoAlcoholicas',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='desayunoAmericano',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='desayunoBuffet',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='desayunoContinental',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='snacks',
        ),
    ]
