# Generated by Django 5.2.7 on 2025-11-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0048_remove_alimentacion_almuerzo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentacion',
            name='price_group_11_20',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='price_group_21_30',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='price_group_31_50',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='price_group_50_plus',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='price_group_5_10',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='price_per_person',
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_11_20_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas) - Temporada Alta'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_11_20_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas) - Temporada Baja'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_11_20_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas) - Temporada Media'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_21_30_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas) - Temporada Alta'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_21_30_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas) - Temporada Baja'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_21_30_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas) - Temporada Media'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_31_50_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas) - Temporada Alta'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_31_50_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas) - Temporada Baja'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_31_50_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas) - Temporada Media'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_50_plus_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas) - Temporada Alta'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_50_plus_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas) - Temporada Baja'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_50_plus_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas) - Temporada Media'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_5_10_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas) - Temporada Alta'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_5_10_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas) - Temporada Baja'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_group_5_10_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas) - Temporada Media'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_per_person_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona - Temporada Alta'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_per_person_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona - Temporada Baja'),
        ),
        migrations.AddField(
            model_name='alimentacion',
            name='price_per_person_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona - Temporada Media'),
        ),
    ]
