# Generated by Django 5.2.7 on 2025-11-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0049_remove_alimentacion_price_group_11_20_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentacion',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='opening_time',
        ),
    ]
