# Generated by Django 5.2.7 on 2025-11-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0050_remove_alimentacion_closing_time_and_more'),
    ]

    operations = [
        # Eliminar campos de fecha de los modelos de servicios (si existen)
        migrations.RemoveField(
            model_name='alimentacion',
            name='fecha_inicio',
            # ignore_not_exists=True,
        ),
        migrations.RemoveField(
            model_name='alimentacion',
            name='fecha_fin',
            # ignore_not_exists=True,
        ),
        migrations.RemoveField(
            model_name='hospedaje',
            name='fecha_inicio',
            # ignore_not_exists=True,
        ),
        migrations.RemoveField(
            model_name='hospedaje',
            name='fecha_fin',
            # ignore_not_exists=True,
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='fecha_inicio',
            # ignore_not_exists=True,
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='fecha_fin',
            # ignore_not_exists=True,
        ),

        # Agregar campo disponible a los modelos de servicios
        migrations.AddField(
            model_name='alimentacion',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
