# Generated by Django 5.2.7 on 2025-11-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0051_auto_20251127_1047'),
    ]

    operations = [
    ]
