# Generated by Django 5.2.7 on 2025-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0052_auto_20251127_1052'),
    ]

    operations = [
        # Agregar campo disponible a los modelos de servicios
        migrations.AddField(
            model_name='alimentacion',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='hospedaje',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='seguro',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
