# Generated by Django 5.2.7 on 2025-11-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0054_remove_alimentacion_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_11_20_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas) - Alta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_11_20_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas) - Baja'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_11_20_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (11-20 personas) - Media'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_21_30_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas) - Alta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_21_30_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas) - Baja'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_21_30_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (21-30 personas) - Media'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_31_50_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas) - Alta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_31_50_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas) - Baja'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_31_50_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (31-50 personas) - Media'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_50_plus_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas) - Alta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_50_plus_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas) - Baja'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_50_plus_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (más de 50 personas) - Media'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_5_10_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas) - Alta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_5_10_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas) - Baja'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_group_5_10_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (5-10 personas) - Media'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_per_person_alta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona - Alta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_per_person_baja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona - Baja'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='price_per_person_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Persona - Media'),
        ),
    ]
