# Generated by Django 5.2.7 on 2025-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0055_alter_alimentacion_price_group_11_20_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenioagencia',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento que aplica en este convenio (ej: 10.00 para 10%)', max_digits=5, verbose_name='% de Descuento'),
        ),
    ]
