# Generated by Django 5.2.7 on 2025-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0056_convenioagencia_porcentaje_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedaje',
            name='tipo_barra',
            field=models.CharField(blank=True, choices=[('Cerrado', 'Bar Cerrado'), ('Abierto', 'Bar Abierto'), ('Libre', 'Barra Libre'), ('Servicio Habitación', 'Servicio a la Habitación'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Barra/Servicio de Bebidas'),
        ),
    ]
