# Generated by Django 5.2.8 on 2025-11-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0057_hospedaje_tipo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='destino',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio/Ciudad'),
        ),
        migrations.AddField(
            model_name='destino',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
    ]
