from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    AlimentacionViewSet,
    DestinoViewSet,
    EntidadViewSet,
    HospedajeViewSet,
    SeguroViewSet,
    TransporteViewSet,
    PaqueteViewSet,
    PaqueteCreateView,
    PaqueteUpdateView,
    PaqueteDeleteView,
    DestinoCreateView,
    DestinoDetailView,
    paquete_crear_ajax,
    destino_editar_individual,
    get_destination_prices,
    EntidadCreateView,
    check_username_availability,
    ajax_login_view,
    dashboard_view,
    ProfileUpdateView,
    get_subcategorias,
    DestinoUpdateView,
    DestinoDeleteView,
    AlimentacionCreateView,
    AlimentacionUpdateView,
    AlimentacionDeleteView,
    SeguroCreateView,
    SeguroUpdateView,
    SeguroDeleteView,
    hospedaje_create_view,
    HospedajeUpdateView,
    HospedajeDeleteView,
    TransporteCreateView,
    TransporteUpdateView,
    TransporteDeleteView,
    delete_account_view, # Añadida esta línea
    search_destinations_and_packages,
    get_destinations_packages_list,
    autocomplete_destinations_and_packages,
    autocomplete_transportes,
    ConvenioAgenciaCreateView,
    ConvenioAgenciaUpdateView,
    ConvenioAgenciaDeleteView,
    convenios_list,
    convenios_agencia_list,
    RutaTransporteCreateView,
    RutaTransporteUpdateView,
    RutaTransporteDeleteView,
    rutas_list,
    rutas_transporte_convenio,
    get_convenio_agencia_info,
    calculate_quotation,
)

router = DefaultRouter()
router.register(r'alimentacion', AlimentacionViewSet)
router.register(r'destinos', DestinoViewSet) # Asegurarse de que esto esté aquí
router.register(r'entidad', EntidadViewSet) # Asegurarse de que esto esté aquí
router.register(r'hospedajes', HospedajeViewSet) # Asegurarse de que esto esté aquí
router.register(r'seguros', SeguroViewSet) # Asegurarse de que esto esté aquí
router.register(r'transportes', TransporteViewSet) # Asegurarse de que esto esté aquí
router.register(r'paquetes', PaqueteViewSet)  # Añadir PaqueteViewSet

urlpatterns = [
    path('entidad/registro/', EntidadCreateView.as_view(), name='entidad-registro'),
    path('paquetes/nuevo/', PaqueteCreateView.as_view(), name='paquete-crear-vista'),
    path('api/paquetes/nuevo/', paquete_crear_ajax, name='paquete-crear'),
    path('paquetes/<int:pk>/editar/', PaqueteUpdateView.as_view(), name='paquete-update'),
    path('paquetes/<int:pk>/eliminar/', PaqueteDeleteView.as_view(), name='paquete-delete'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('subcategorias/', get_subcategorias, name='api_get_subcategorias'),
    path('', include(router.urls)),
    path('destinos/nuevo/', DestinoCreateView.as_view(), name='destino-crear'),
    path('destino/<int:pk>/update/', DestinoUpdateView.as_view(), name='destino-update'),
    path('destino/<int:pk>/delete/', DestinoDeleteView.as_view(), name='destino-delete'),
    path('destino/<int:pk>/editar/', destino_editar_individual, name='destino-editar-individual'),
    path('alimentacion/nuevo/', AlimentacionCreateView.as_view(), name='alimentacion-crear'),
    path('alimentacion/<int:pk>/update/', AlimentacionUpdateView.as_view(), name='alimentacion-update'),
    path('alimentacion/<int:pk>/delete/', AlimentacionDeleteView.as_view(), name='alimentacion-delete'),
    path('hospedaje/nuevo/', hospedaje_create_view, name='hospedaje-crear'),
    path('hospedaje/<int:pk>/update/', HospedajeUpdateView.as_view(), name='hospedaje-update'),
    path('hospedaje/<int:pk>/delete/', HospedajeDeleteView.as_view(), name='hospedaje-delete'),
    path('seguro/nuevo/', SeguroCreateView.as_view(), name='seguro-crear'),
    path('seguro/<int:pk>/update/', SeguroUpdateView.as_view(), name='seguro-update'),
    path('seguro/<int:pk>/delete/', SeguroDeleteView.as_view(), name='seguro-delete'),
    path('transporte/nuevo/', TransporteCreateView.as_view(), name='transporte-crear'),
    path('transporte/<int:pk>/update/', TransporteUpdateView.as_view(), name='transporte-update'),
    path('transporte/<int:pk>/delete/', TransporteDeleteView.as_view(), name='transporte-delete'),
    path('destino/<int:pk>/', DestinoDetailView.as_view(), name='destino-detail'),
    path('api/destinos/precios/', get_destination_prices, name='api-destinos-precios'),

    path('check_username/', check_username_availability, name='check_username_availability'),
    path('ajax/login/', ajax_login_view, name='ajax_login'),
    path('profile/delete/', delete_account_view, name='delete_account'),
    path('api/search-destinations-packages/', search_destinations_and_packages, name='search_destinations_packages'),
    path('api/autocomplete-destinations-packages/', autocomplete_destinations_and_packages, name='autocomplete_destinations_packages'),
    path('api/get-destinations-packages/', get_destinations_packages_list, name='get_destinations_packages'),
    path('api/autocomplete-transportes/', autocomplete_transportes, name='autocomplete_transportes'),

    path('convenios/', convenios_list, name='convenios-list'),
    path('convenios-agencia/', convenios_agencia_list, name='convenios-agencia-list'),
    path('convenios-agencia/nuevo/', ConvenioAgenciaCreateView.as_view(), name='convenio-agencia-crear'),
    path('convenios-agencia/<int:pk>/editar/', ConvenioAgenciaUpdateView.as_view(), name='convenio-agencia-update'),
    path('convenios-agencia/<int:pk>/eliminar/', ConvenioAgenciaDeleteView.as_view(), name='convenio-agencia-delete'),

    path('rutas/', rutas_list, name='rutas-list'),
    path('rutas/nuevo/', RutaTransporteCreateView.as_view(), name='ruta-transporte-crear'),
    path('rutas/<int:pk>/editar/', RutaTransporteUpdateView.as_view(), name='ruta-transporte-update'),
    path('rutas/<int:pk>/eliminar/', RutaTransporteDeleteView.as_view(), name='ruta-transporte-delete'),
    path('rutas/convenio/<int:convenio_id>/', rutas_transporte_convenio, name='rutas-convenio'),
    path('api/convenio-agencia/<int:convenio_id>/', get_convenio_agencia_info, name='get_convenio_agencia_info'),
    path('calcular-cotizacion/', calculate_quotation, name='calcular_cotizacion'),
]